import cyc1 from "./images/cycle1.jfif";
import cyc2 from "./images/cycle2.jfif";
import cyc3 from "./images/cycle3.jfif";
import cyc4 from "./images/cycle4.jfif";
import cyc5 from "./images/cycle5.jfif";
import cyc6 from "./images/cycle6.jfif";
import cyc7 from "./images/cycle7.jfif";
import cyc8 from "./images/cycle8.jfif";
import cyc9 from "./images/cycle9.jfif";
import cyc10 from "./images/cycle10.jfif";
import cyc11 from "./images/cycle11.jfif";
import cyc12 from "./images/cycle12.jfif";
import logo from "./images/logo.jpeg";
import col1 from "./images/col1.png";
import col2 from "./images/col2.png";
import col3 from "./images/col3.png";
import col4 from "./images/col4.png";
import col5 from "./images/col5.png";
import col6 from "./images/col6.png";
import col7 from "./images/col7.png";
import col8 from "./images/col8.png";
import col9 from "./images/col9.png";
import col10 from "./images/col10.png";
import col11 from "./images/col11.png";
import menlg from "./images/men.jpg";
import footlogo1 from "./images/footlogo.jpeg";
import footlogo2 from "./images/footlogoe.jpeg";

export const CYC_1 = cyc1;
export const CYC_2 = cyc2;
export const CYC_3 = cyc3;
export const CYC_4 = cyc4;
export const CYC_5 = cyc5;
export const CYC_6 = cyc6;
export const CYC_7 = cyc7;
export const CYC_8 = cyc8;
export const CYC_9 = cyc9;
export const CYC_10 = cyc10;
export const CYC_11 = cyc11;
export const CYC_12 = cyc12;
export const LOGOE = logo;
export const COL1 = col1;
export const COL2 = col2;
export const COL3 = col3;
export const COL4 = col4;
export const COL5 = col5;
export const COL6 = col6;
export const COL7 = col7;
export const COL8 = col8;
export const COL9 = col9;
export const COL10 = col10;
export const COL11 = col11;
export const MEN = menlg;
export const FOOTLOGO = footlogo1;
export const FOOTLOGOE = footlogo2;
